/*
MySQL Data Transfer
Source Host: localhost
Source Database: l1jdb_cn
Target Host: localhost
Target Database: l1jdb_cn
Date: 2011-7-9 ���� 07:34:55
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for william_system_message
-- ----------------------------
CREATE TABLE `william_system_message` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `message` varchar(1000) NOT NULL,
  `note` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=20001 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `william_system_message` VALUES ('1001', 'true', '怪对怪放魔法 (单体攻击)(true)(false)');
INSERT INTO `william_system_message` VALUES ('1002', 'true', '免登出可以把能力值点完(true)(false)');
INSERT INTO `william_system_message` VALUES ('1003', 'true', '玩家间ＰＫ获胜广播');
INSERT INTO `william_system_message` VALUES ('1004', '携带时使用部分辅助魔法，无需吟唱，但是会消耗魔法徽章一枚。', '');
INSERT INTO `william_system_message` VALUES ('1005', '【奇岩竞技场】５分钟后比赛将开始，想参赛者请赶快入场。', '无限大战广播信息');
INSERT INTO `william_system_message` VALUES ('1006', '【威顿竞技场】５分钟后比赛将开始，想参赛者请赶快入场。', '无限大战广播信息');
INSERT INTO `william_system_message` VALUES ('1007', '【古鲁丁竞技场】５分钟后比赛将开始，想参赛者请赶快入场。', '无限大战广播信息');
INSERT INTO `william_system_message` VALUES ('1008', '【说话之岛竞技场】５分钟后比赛将开始，想参赛者请赶快入场。', '无限大战广播信息');
INSERT INTO `william_system_message` VALUES ('1009', '【银骑士竞技场】５分钟后比赛将开始，想参赛者请赶快入场。', '无限大战广播信息');
INSERT INTO `william_system_message` VALUES ('1010', '目前没有可配置的守城警卫。', '');
INSERT INTO `william_system_message` VALUES ('1011', '守城警卫已经配置完毕。', '');
INSERT INTO `william_system_message` VALUES ('1012', '城门完全被破坏了。', '');
INSERT INTO `william_system_message` VALUES ('1013', '城门已经受损。', '');
INSERT INTO `william_system_message` VALUES ('1014', '能力值已经重置。', '');
INSERT INTO `william_system_message` VALUES ('1015', '还有重置点数未使用。', '');
INSERT INTO `william_system_message` VALUES ('1016', '已经携带一名随身祭司了。', '');
INSERT INTO `william_system_message` VALUES ('1017', '对你使用偷窥卡，不过没有偷窥成功。', '');
INSERT INTO `william_system_message` VALUES ('1018', '使用反偷窥卡，因此偷窥失败。', '');
INSERT INTO `william_system_message` VALUES ('1019', '装备中无法强化', '');
INSERT INTO `william_system_message` VALUES ('1020', '已强化成', '装备强化水晶成功信息');
INSERT INTO `william_system_message` VALUES ('1021', '强化失败', '装备强化水晶失败信息');
INSERT INTO `william_system_message` VALUES ('1022', '所持有的金币', '');
INSERT INTO `william_system_message` VALUES ('1023', '超过20亿，无法检取', '');
INSERT INTO `william_system_message` VALUES ('1024', '你的血盟成员在你无法传送前往的地区。', '');
INSERT INTO `william_system_message` VALUES ('1025', '产生机率性反击魔法伤害的效果。', '');
INSERT INTO `william_system_message` VALUES ('1026', '无法交易', '');
INSERT INTO `william_system_message` VALUES ('1027', '等级', '');
INSERT INTO `william_system_message` VALUES ('1028', '以下才可以使用。', '');
INSERT INTO `william_system_message` VALUES ('1029', '目标在安全区域内，负面性魔法施放失败。', '');
INSERT INTO `william_system_message` VALUES ('1221', '你的武器已获得祝福!', '魔法武器强化宝石失败');
INSERT INTO `william_system_message` VALUES ('1222', '嗜血的', null);
INSERT INTO `william_system_message` VALUES ('1223', '偷窃之', null);
INSERT INTO `william_system_message` VALUES ('1224', '冻结的', null);
INSERT INTO `william_system_message` VALUES ('1225', '闪避之', null);
INSERT INTO `william_system_message` VALUES ('1226', '地之', null);
INSERT INTO `william_system_message` VALUES ('1227', '崩裂', null);
INSERT INTO `william_system_message` VALUES ('1228', '地灵', null);
INSERT INTO `william_system_message` VALUES ('1229', '火之', null);
INSERT INTO `william_system_message` VALUES ('1230', '爆炎', null);
INSERT INTO `william_system_message` VALUES ('1231', '火灵', null);
INSERT INTO `william_system_message` VALUES ('1232', '水之', null);
INSERT INTO `william_system_message` VALUES ('1233', '海啸', null);
INSERT INTO `william_system_message` VALUES ('1234', '水灵', null);
INSERT INTO `william_system_message` VALUES ('1235', '风之', null);
INSERT INTO `william_system_message` VALUES ('1236', '暴风', null);
INSERT INTO `william_system_message` VALUES ('1237', '风灵', null);
INSERT INTO `william_system_message` VALUES ('1238', '从', null);
INSERT INTO `william_system_message` VALUES ('1239', '吸取到', null);
INSERT INTO `william_system_message` VALUES ('1240', '血量', null);
INSERT INTO `william_system_message` VALUES ('1241', '你被', null);
INSERT INTO `william_system_message` VALUES ('1242', '偷走', null);
INSERT INTO `william_system_message` VALUES ('1243', '金币', null);
INSERT INTO `william_system_message` VALUES ('1244', '偷取到', null);
INSERT INTO `william_system_message` VALUES ('1245', '目标已经没有钱了', null);
INSERT INTO `william_system_message` VALUES ('1086', '你被系统侦测到速度异常，请原地休息１６秒', '');
INSERT INTO `william_system_message` VALUES ('1087', '神秘的力量已经消失', '');
INSERT INTO `william_system_message` VALUES ('1088', '受到神秘的力量影响，获得的经验值加倍了', '');
INSERT INTO `william_system_message` VALUES ('1089', '系统侦测到', '');
INSERT INTO `william_system_message` VALUES ('1090', '行走速度异常，已被强制断线。', '');
INSERT INTO `william_system_message` VALUES ('1091', '时间', '');
INSERT INTO `william_system_message` VALUES ('1092', '攻击速度异常，已被强制断线。', '');
INSERT INTO `william_system_message` VALUES ('1093', '万能药已达到使用上限', '');
INSERT INTO `william_system_message` VALUES ('1094', '系统侦测到玩家', '');
INSERT INTO `william_system_message` VALUES ('1095', '移动速度异常', '');
INSERT INTO `william_system_message` VALUES ('1096', '攻击速度异常', '');
INSERT INTO `william_system_message` VALUES ('1097', '职业必须是', '');
INSERT INTO `william_system_message` VALUES ('1098', '魅力最低需求', '');
INSERT INTO `william_system_message` VALUES ('1099', '等级需求', '');
INSERT INTO `william_system_message` VALUES ('1100', '以上，才可以解此任务', '');
INSERT INTO `william_system_message` VALUES ('1101', '你的职业无法解此任务', '');
INSERT INTO `william_system_message` VALUES ('1102', '需要特定的变身才能解此任务', '');
INSERT INTO `william_system_message` VALUES ('1103', '已经解过此任务', '');
INSERT INTO `william_system_message` VALUES ('1104', '已经取得指定道具', '');
INSERT INTO `william_system_message` VALUES ('1105', '恭喜', '');
INSERT INTO `william_system_message` VALUES ('1106', '使用', '');
INSERT INTO `william_system_message` VALUES ('1107', '杀死了', '');
INSERT INTO `william_system_message` VALUES ('1108', '经验加倍', '');
INSERT INTO `william_system_message` VALUES ('1109', '分钟', '');
INSERT INTO `william_system_message` VALUES ('1110', '经验加倍剩下', '');
INSERT INTO `william_system_message` VALUES ('1111', '秒', '');
INSERT INTO `william_system_message` VALUES ('1112', '受到神秘力量的祝福，获得的经验值加倍了', '');
INSERT INTO `william_system_message` VALUES ('1113', '必须有', '');
INSERT INTO `william_system_message` VALUES ('1114', '才能使用此道具', '');
INSERT INTO `william_system_message` VALUES ('1115', '以上', '');
INSERT INTO `william_system_message` VALUES ('1116', '偷听到', '');
INSERT INTO `william_system_message` VALUES ('1117', '说话之岛', '');
INSERT INTO `william_system_message` VALUES ('1118', '银骑士', '');
INSERT INTO `william_system_message` VALUES ('1119', '奇岩', '');
INSERT INTO `william_system_message` VALUES ('1120', '古鲁丁', '');
INSERT INTO `william_system_message` VALUES ('1121', '威顿', '');
INSERT INTO `william_system_message` VALUES ('1122', '竞技场', '');
INSERT INTO `william_system_message` VALUES ('1123', '分钟后比赛将开始，想参赛者请现在入场', '');
INSERT INTO `william_system_message` VALUES ('1124', '的', '');
INSERT INTO `william_system_message` VALUES ('1125', '系统公告', '');
INSERT INTO `william_system_message` VALUES ('1126', '经验值倍率已调整为', '');
INSERT INTO `william_system_message` VALUES ('1127', '倍', '');
INSERT INTO `william_system_message` VALUES ('1128', '目前的经验值倍率为', '');
INSERT INTO `william_system_message` VALUES ('1129', '掉宝率已调整为', '');
INSERT INTO `william_system_message` VALUES ('1130', '目前的掉宝率为', '');
INSERT INTO `william_system_message` VALUES ('1131', 'exp', 'GM指令(可自行改成中文)');
INSERT INTO `william_system_message` VALUES ('1132', 'drop', 'GM指令(可自行改成中文)');
INSERT INTO `william_system_message` VALUES ('1133', 'register', 'GM指令(可自行改成中文)');
INSERT INTO `william_system_message` VALUES ('1134', '注册新帐号功能已关闭', '');
INSERT INTO `william_system_message` VALUES ('1135', '注册新帐号功能已开启', '');
INSERT INTO `william_system_message` VALUES ('1136', '熊猫', '');
INSERT INTO `william_system_message` VALUES ('1137', '项圈[Lv.1 熊猫]', '');
INSERT INTO `william_system_message` VALUES ('1138', '袋鼠', '');
INSERT INTO `william_system_message` VALUES ('1139', '项圈[Lv.1 袋鼠]', '');
INSERT INTO `william_system_message` VALUES ('1140', '装备中无法溶解', '');
INSERT INTO `william_system_message` VALUES ('1141', '龙骑士书板', null);
INSERT INTO `william_system_message` VALUES ('1142', '记忆水晶', null);
INSERT INTO `william_system_message` VALUES ('1143', '恭喜你的武器强化成功!', '99%武器加成卷轴提示信息');
INSERT INTO `william_system_message` VALUES ('1144', '恭喜你的防具强化成功!', '99%防具加成卷轴提示信息');
INSERT INTO `william_system_message` VALUES ('1145', '武器攻击值已达到最高点,不能再冲了!', '99%武器加成卷轴提示信息');
INSERT INTO `william_system_message` VALUES ('1146', '防具值已达到最高点,不能再冲了!', '99%防具加成卷轴提示信息');
INSERT INTO `william_system_message` VALUES ('1147', '你骰出的点数是 [ ', '魔法筛子提示信息');
INSERT INTO `william_system_message` VALUES ('1148', '点数为 [ 豹子 ]', '魔法筛子提示信息');
INSERT INTO `william_system_message` VALUES ('1149', '点数为 [ 小 ]', '魔法筛子提示信息');
INSERT INTO `william_system_message` VALUES ('1150', '点数为 [ 中 ]', '魔法筛子提示信息');
INSERT INTO `william_system_message` VALUES ('1151', '点数为 [ 大 ]', '魔法筛子提示信息');
INSERT INTO `william_system_message` VALUES ('1152', '你的HP值永久增加10点!', '万能药HP提示信息');
INSERT INTO `william_system_message` VALUES ('1153', '你的MP值永久增加10点!', '万能药MP提示信息');
INSERT INTO `william_system_message` VALUES ('1154', '你的HP值已到可增加上限!', '万能药HP提示信息');
INSERT INTO `william_system_message` VALUES ('1155', '你的MP值已到可增加上限!', '万能药MP提示信息');
INSERT INTO `william_system_message` VALUES ('1156', '\\f3【管理员】', 'AccessLevel 200');
INSERT INTO `william_system_message` VALUES ('1157', '\\fM【VIP1】', 'AccessLevel 1');
INSERT INTO `william_system_message` VALUES ('1158', '\\fV【VIP2】', 'AccessLevel 2');
INSERT INTO `william_system_message` VALUES ('1159', '\\fD【VIP3】', 'AccessLevel 3');
INSERT INTO `william_system_message` VALUES ('1160', '\\fM【新兵】', '1-2');
INSERT INTO `william_system_message` VALUES ('1161', '\\fM【下等兵】', '3-6');
INSERT INTO `william_system_message` VALUES ('1162', '\\fM【中等兵】', '7-14');
INSERT INTO `william_system_message` VALUES ('1163', '\\fM【上等兵】', '15-28');
INSERT INTO `william_system_message` VALUES ('1164', '\\fM【少尉】', '29-56');
INSERT INTO `william_system_message` VALUES ('1165', '\\fM【中尉】', '57-111');
INSERT INTO `william_system_message` VALUES ('1166', '\\fM【上尉】', '112-223');
INSERT INTO `william_system_message` VALUES ('1167', '\\fM【少校】', '224-447');
INSERT INTO `william_system_message` VALUES ('1168', '\\fM【中校】', '448-859');
INSERT INTO `william_system_message` VALUES ('1169', '\\fM【上校】', '860-1791');
INSERT INTO `william_system_message` VALUES ('1170', '\\fM【大校】', '1792-3583');
INSERT INTO `william_system_message` VALUES ('1171', '\\fM【三星少将】', '3584-7167');
INSERT INTO `william_system_message` VALUES ('1172', '\\fM【四星中将】', '7168-14334');
INSERT INTO `william_system_message` VALUES ('1173', '\\fM【五星上将】', '14335-15000');
INSERT INTO `william_system_message` VALUES ('1174', '\\fM【三军统帅】', '15001');
INSERT INTO `william_system_message` VALUES ('1175', '\\f3【管理助理】', 'AccessLevel 100');
INSERT INTO `william_system_message` VALUES ('1176', 'fY【下等兵】', '3-6');
INSERT INTO `william_system_message` VALUES ('1177', 'fY【中等兵】', '7-14');
INSERT INTO `william_system_message` VALUES ('1178', 'fY【上等兵】', '15-28');
INSERT INTO `william_system_message` VALUES ('1179', 'fY【少尉】', '29-56');
INSERT INTO `william_system_message` VALUES ('1180', 'fY【中尉】', '57-111');
INSERT INTO `william_system_message` VALUES ('1181', 'fY【上尉】', '112-223');
INSERT INTO `william_system_message` VALUES ('1182', 'fY【少校】', '224-447');
INSERT INTO `william_system_message` VALUES ('1183', 'fY【中校】', '448-859');
INSERT INTO `william_system_message` VALUES ('1184', 'fY【上校】', '896-1791');
INSERT INTO `william_system_message` VALUES ('1185', 'fY【大校】', '1792-3583');
INSERT INTO `william_system_message` VALUES ('1186', 'fY【三星少将】', '3584-7167');
INSERT INTO `william_system_message` VALUES ('1187', 'fY【四星中将】', '7168-14334');
INSERT INTO `william_system_message` VALUES ('1188', 'fY【五星上将】', '14335-15000');
INSERT INTO `william_system_message` VALUES ('1189', 'fY【三军统帅】', '15000');
INSERT INTO `william_system_message` VALUES ('1190', '您的功勋点数上升了1点。', '功勋证明令使用提示');
INSERT INTO `william_system_message` VALUES ('1191', '赌博赛场是不可以隐身的!', '无效');
INSERT INTO `william_system_message` VALUES ('1192', ' 强化成功', '武器攻击强化宝石成功提示');
INSERT INTO `william_system_message` VALUES ('1193', ' 强化失败', '武器攻击强化宝石失败提示');
INSERT INTO `william_system_message` VALUES ('1194', '你已成功加入会员.输入-help查看会员命令.', '会员证明 AccessLevel 1');
INSERT INTO `william_system_message` VALUES ('1195', '下次您将以“VIP2”身份登陆。', '会员证明 AccessLevel 2');
INSERT INTO `william_system_message` VALUES ('1196', '下次您将以“VIP3”身份登陆。', '会员证明 AccessLevel 3');
INSERT INTO `william_system_message` VALUES ('1197', 'ＧＭ不能使用此物品，此物品为会员才可以使用。', '会员证明GM不可使用');
INSERT INTO `william_system_message` VALUES ('1198', '你的武器得到了魔法的祝福。', '魔法武器强化宝石成功');
INSERT INTO `william_system_message` VALUES ('1199', '目前功勋：', '官阶证明书提示信息');
INSERT INTO `william_system_message` VALUES ('1200', '。目前地位：', '官阶证明书提示信息');
INSERT INTO `william_system_message` VALUES ('1201', '晋升差额：', '官阶证明书提示信息');
INSERT INTO `william_system_message` VALUES ('1202', '。晋升军阶：', '官阶证明书提示信息');
INSERT INTO `william_system_message` VALUES ('1203', '在线时间：', '官阶证明书提示信息');
INSERT INTO `william_system_message` VALUES ('1204', '。', '官阶证明书提示信息');
INSERT INTO `william_system_message` VALUES ('1205', '获得1等大奖 10万元', '魔法筛子1');
INSERT INTO `william_system_message` VALUES ('1206', '获得安慰奖 1元', '魔法筛子1');
INSERT INTO `william_system_message` VALUES ('1207', '获得2等奖 1万元', '魔法筛子1');
INSERT INTO `william_system_message` VALUES ('1208', '获得3等奖 2千元', '魔法筛子1');
INSERT INTO `william_system_message` VALUES ('1209', '获得1等大奖 30万元', '魔法筛子2');
INSERT INTO `william_system_message` VALUES ('1210', '获得安慰奖 100元', '魔法筛子2');
INSERT INTO `william_system_message` VALUES ('1211', '获得2等奖 5万元', '魔法筛子2');
INSERT INTO `william_system_message` VALUES ('1212', '获得3等奖 2万元', '魔法筛子2');
INSERT INTO `william_system_message` VALUES ('1213', '获得1等大奖 50万元', '魔法筛子3');
INSERT INTO `william_system_message` VALUES ('1214', '获得安慰奖 5千元', '魔法筛子3');
INSERT INTO `william_system_message` VALUES ('1215', '获得2等奖 8万元', '魔法筛子3');
INSERT INTO `william_system_message` VALUES ('1216', '获得3等奖 3万元', '魔法筛子3');
INSERT INTO `william_system_message` VALUES ('1217', '获得1等大奖 100万元', '魔法筛子4');
INSERT INTO `william_system_message` VALUES ('1218', '获得安慰奖 1万元', '魔法筛子4');
INSERT INTO `william_system_message` VALUES ('1219', '获得2等奖 8万元', '魔法筛子4');
INSERT INTO `william_system_message` VALUES ('1220', '获得3等奖 3万元', '魔法筛子4');
INSERT INTO `william_system_message` VALUES ('1246', '被冻结三秒', '魔法武器冰冻');
INSERT INTO `william_system_message` VALUES ('1247', '巧妙的躲过了', '魔法武器闪避');
INSERT INTO `william_system_message` VALUES ('1248', '的攻击', '魔法武器闪避');
INSERT INTO `william_system_message` VALUES ('1249', '你的攻击被', null);
INSERT INTO `william_system_message` VALUES ('1250', '属性伤害', null);
INSERT INTO `william_system_message` VALUES ('1251', '。', null);
INSERT INTO `william_system_message` VALUES ('1252', '除了你，其他角色已回到奇岩村。', '解卡点卷轴');
INSERT INTO `william_system_message` VALUES ('1253', '武器没有获得祝福!', null);
INSERT INTO `william_system_message` VALUES ('1254', '小时', '道具、装备剩余时间');
INSERT INTO `william_system_message` VALUES ('1255', '请不要仍垃圾.', '道具不可丢弃提示信息');
INSERT INTO `william_system_message` VALUES ('1256', '你不能随便扔给npc东西', '不能给NPC东西提示信息');
INSERT INTO `william_system_message` VALUES ('1257', '此物品在这个地图是不可使用的，如果想逃跑小退即可！', 'PK赌博场不能使用物品提示');
INSERT INTO `william_system_message` VALUES ('1258', '除了你，其他角色已回到奇岩村。', '解卡点卷轴提示信息50003');
INSERT INTO `william_system_message` VALUES ('1259', ' 玩家对你使用了偷窥卡,不过没有偷窥成功!', '反偷窥卡提示信息51018');
INSERT INTO `william_system_message` VALUES ('1260', ' 玩家使用反偷窥卡,因此偷窥失败!', '反偷窥卡提示信息51018');
INSERT INTO `william_system_message` VALUES ('1261', '你看到你的等级降到了9级!!', '洗血药水提示信息60003');
INSERT INTO `william_system_message` VALUES ('1262', '你要到70以上洗血才可以使用!!', '洗血药水提示信息60003');
INSERT INTO `william_system_message` VALUES ('1263', '你的正义长了32760.', '正义药水提示信息60006');
INSERT INTO `william_system_message` VALUES ('1264', '请在正义为32760以下使用!!', '正义药水提示信息60006');
INSERT INTO `william_system_message` VALUES ('1265', '身体感觉充满魔力!!', '灵魂转换提示信息60007');
INSERT INTO `william_system_message` VALUES ('1266', '你的血低于500点是不可以使用!!', '灵魂转换提示信息60007');
INSERT INTO `william_system_message` VALUES ('1267', '经验加倍药水时间剩余 ', '经验加倍药水剩余时间信息');
INSERT INTO `william_system_message` VALUES ('1268', ' 秒', '经验加倍药水剩余时间信息');
INSERT INTO `william_system_message` VALUES ('1269', '1.5倍经验药水启动! ', '1.5倍经验药水提示信息');
INSERT INTO `william_system_message` VALUES ('1270', '2倍经验药水启动! ', '2倍经验药水提示信息');
INSERT INTO `william_system_message` VALUES ('1271', '2.5倍经验药水启动! ', '2.5倍经验药水提示信息');
INSERT INTO `william_system_message` VALUES ('1272', '玩家【', '赌博PK信息');
INSERT INTO `william_system_message` VALUES ('1273', '】受不了对手折磨,已经顺利逃跑!', '赌博PK信息');
INSERT INTO `william_system_message` VALUES ('1274', '此装备不可强化。', '装备强化水晶不可强化信息');
INSERT INTO `william_system_message` VALUES ('1275', '\"屾﹌o﹌屾可憐的 【', 'BOSS死亡信息');
INSERT INTO `william_system_message` VALUES ('1276', ' 】被', 'BOSS死亡信息');
INSERT INTO `william_system_message` VALUES ('1277', ' 殺爆了！', 'BOSS死亡信息');
INSERT INTO `william_system_message` VALUES ('1278', '恭喜玩家 【', '玩家被BOSS打死信息');
INSERT INTO `william_system_message` VALUES ('1279', '】 被怪物 【', '玩家被BOSS打死信息');
INSERT INTO `william_system_message` VALUES ('1280', '】 砍爆头了!', '玩家被BOSS打死信息');
INSERT INTO `william_system_message` VALUES ('1281', '◆强盗', 'PK死亡信息');
INSERT INTO `william_system_message` VALUES ('1282', ' 打爆了玩家 ', 'PK死亡信息');
INSERT INTO `william_system_message` VALUES ('1283', ' 地球很危险,快回火星吧◆', 'PK死亡信息');
INSERT INTO `william_system_message` VALUES ('1284', '恭喜玩家 【', '召唤兽打死BOSS信息');
INSERT INTO `william_system_message` VALUES ('1285', '】 的召唤兽 【', '召唤兽打死BOSS信息');
INSERT INTO `william_system_message` VALUES ('1286', '】杀死了 【', '召唤兽打死BOSS信息');
INSERT INTO `william_system_message` VALUES ('1287', '】', '召唤兽打死BOSS信息');
INSERT INTO `william_system_message` VALUES ('1288', '必須召喚出該寵物才能進行更名動作。', '宠物更名卷轴');
INSERT INTO `william_system_message` VALUES ('1289', '恭喜你中了 ', ' 彩票号码信息');
INSERT INTO `william_system_message` VALUES ('1290', ' 个号码!', ' 彩票号码信息');
INSERT INTO `william_system_message` VALUES ('1291', '恭喜你中了普通奖!', '彩票中奖信息');
INSERT INTO `william_system_message` VALUES ('1292', '恭喜你中了3等奖!', '彩票中奖信息');
INSERT INTO `william_system_message` VALUES ('1293', '恭喜你中了2等奖!', '彩票中奖信息');
INSERT INTO `william_system_message` VALUES ('1294', '恭喜你中了1等奖!', '彩票中奖信息');
INSERT INTO `william_system_message` VALUES ('1295', '你已经喝了此类药水,不能积累使用!', null);
INSERT INTO `william_system_message` VALUES ('1296', '你感觉此时经验加倍，时间是900秒效果,请不要小退相消!', null);
INSERT INTO `william_system_message` VALUES ('1297', '此物品在这个地图是不能使用！', '赌博物品不可使用信息');
INSERT INTO `william_system_message` VALUES ('1298', '赛程设置10分钟一场，如果没有比赛玩家，你可以小退或者点管理员离开!', '赌博观看信息');
INSERT INTO `william_system_message` VALUES ('1299', '参赛人员已经满员,请等比赛结束后才进入观看比赛！', '赌博观看信息');
INSERT INTO `william_system_message` VALUES ('1300', '要想观看比赛你的等级必须高于60,才可进入观看!', '赌博观看信息');
INSERT INTO `william_system_message` VALUES ('1301', '玩家【', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1302', '】进入战斗正准备和对手拼命过招...!', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1303', '给你可以出去的卷轴.', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1304', '参赛人员已经满员,请等比赛结束后才进入参加比赛！', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1305', '要想参加比赛你的银行存款必须有1000万以上才可进入参加！', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1306', '要想参加比赛你的等级必须高于65,才可进入参加!', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1307', '你必须解除隐身,如果你是法师黑妖将自己无所出来,其他职业将隐斗脱掉,否则进入地图无法战斗!', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1308', '挑战时间开始：记时10分钟', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1309', '该地图人数已满，请稍等...', '赌博参加信息');
INSERT INTO `william_system_message` VALUES ('1310', '您已经有了军阶证明书。', '军阶证明书兑换信息');
INSERT INTO `william_system_message` VALUES ('1311', '这是您的“军阶证明书”请收好，不要删除了哦。', '军阶证明书兑换信息');
INSERT INTO `william_system_message` VALUES ('1312', '您身上的黄金不够10个。', '军阶证明书兑换信息');
INSERT INTO `william_system_message` VALUES ('1313', '这是您的“功勋证明令”请收好，不要删除了哦。', '功勋证明令兑换信息');
INSERT INTO `william_system_message` VALUES ('1314', '您身上的黄金不够100个。', '功勋证明令兑换信息');
INSERT INTO `william_system_message` VALUES ('1315', '【 ', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1317', '您的功勋不足,军阶无法提升至【下等兵】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1316', ' 】', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1318', 'fR→恭喜新兵', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1319', '军阶晋升至[下等兵]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1320', '因为你优异的表现，获得10W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1321', '您的功勋不足,军阶无法提升至【中等兵】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1322', 'fR→恭喜下等兵', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1323', '军阶晋升至[中等兵]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1324', '因为你优异的表现，获得20W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1325', '您的功勋不足,军阶无法提升至【上等兵】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1326', 'fR→恭喜中等兵', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1327', '军阶晋升至[上等兵]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1328', '因为你优异的表现，获得一套上等兵装备和50W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1329', '您的功勋不足,军阶无法提升至【少尉】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1330', 'fR→恭喜上等兵', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1331', '军阶晋升至[少尉]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1332', '因为你优异的表现，获得一件少尉装备和200W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1333', '您的功勋不足,军阶无法提升至【中尉】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1334', 'fR→恭喜少尉', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1335', '军阶晋升至[中尉]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1336', '因为你优异的表现，获得一件中尉装备和400W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1337', '您的功勋不足,军阶无法提升至【上尉】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1338', 'fR→恭喜中尉', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1339', '军阶晋升至[上尉]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1340', '因为你优异的表现，获得一件上尉装备和600W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1341', '您的功勋不足,军阶无法提升至【少校】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1342', 'fR→恭喜上尉', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1343', '军阶晋升至[少校]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1344', '因为你优异的表现，获得一件少校装备和800W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1345', '您的功勋不足,军阶无法提升至【中校】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1346', 'fR→恭喜少校', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1347', '军阶晋升至[中校]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1348', '因为你优异的表现，获得一件中校装备和1500W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1349', '您的功勋不足,军阶无法提升至【上校】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1350', 'fR→恭喜中校', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1351', '军阶晋升至[上校]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1352', '因为你优异的表现，获得一件上校装备和2000W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1353', '您的功勋不足,军阶无法提升至【大校】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1354', 'fR→恭喜上校', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1355', '军阶晋升至[大校]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1356', '因为你优异的表现，获得一件上校装备和3000W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1357', '您的功勋不足,军阶无法提升至【三星少将】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1358', 'fR→恭喜大校', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1359', '军阶晋升至[三星少将]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1360', '因为你优异的表现，获得两件三星少将武器和4000W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1361', '您的功勋不足,军阶无法提升至【四星中将】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1362', 'fR→恭喜三星少将', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1363', '军阶晋升至[四星中将]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1364', '因为你优异的表现，获得两件四星中将装备和5000W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1365', '您的功勋不足,军阶无法提升至【五星上将】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1366', 'fR→恭喜四星中将', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1367', '军阶晋升至[五星上将]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1368', '因为你优异的表现，获得两件五星装备和8000W金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1369', '您的功勋不足,军阶无法提升至【三军统帅】。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1370', 'fR→恭喜五星上将', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1371', '军阶晋升至[三军统帅]←', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1372', '因为你优异的表现，获得一套三军统帅装备和1E金币的奖励，请继续努力。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1373', '你已经是最高军阶。', '军阶提升信息');
INSERT INTO `william_system_message` VALUES ('1374', '你成功取款(1000000)。', '银行取款信息');
INSERT INTO `william_system_message` VALUES ('1375', '你成功取款(5000000)。', '银行取款信息');
INSERT INTO `william_system_message` VALUES ('1376', '你成功取款(10000000)。', '银行取款信息');
INSERT INTO `william_system_message` VALUES ('1377', '你成功取款(30000000)。', '银行取款信息');
INSERT INTO `william_system_message` VALUES ('1378', '你获得 ', 'who信息');
INSERT INTO `william_system_message` VALUES ('1379', ' 税金.', 'who信息');
INSERT INTO `william_system_message` VALUES ('1380', '当前共有→ ', 'who信息');
INSERT INTO `william_system_message` VALUES ('1381', ' ←名玩家在线上。', 'who信息');
INSERT INTO `william_system_message` VALUES ('1382', ' 倍', 'who信息');
INSERT INTO `william_system_message` VALUES ('1383', '㊣ 服务器设定 ㊣', 'who信息');
INSERT INTO `william_system_message` VALUES ('1384', '【经验值】', 'who信息');
INSERT INTO `william_system_message` VALUES ('1385', ' 倍  【正义值】', 'who信息');
INSERT INTO `william_system_message` VALUES ('1386', '【友好度】', 'who信息');
INSERT INTO `william_system_message` VALUES ('1387', ' 倍 【负重率】', 'who信息');
INSERT INTO `william_system_message` VALUES ('1388', '【掉宝率】', 'who信息');
INSERT INTO `william_system_message` VALUES ('1389', ' 倍  【掉钱率】', 'who信息');
INSERT INTO `william_system_message` VALUES ('1390', '【冲武器】', 'who信息');
INSERT INTO `william_system_message` VALUES ('1391', ' %  【冲防具】', 'who信息');
INSERT INTO `william_system_message` VALUES ('1392', ' %', 'who信息');
INSERT INTO `william_system_message` VALUES ('1393', '', 'who信息');
INSERT INTO `william_system_message` VALUES ('1394', '. 玩家:{ ', 'who信息');
INSERT INTO `william_system_message` VALUES ('1395', ' }、血盟:{ ', 'who信息');
INSERT INTO `william_system_message` VALUES ('1396', ' }、等级:{ ', 'who信息');
INSERT INTO `william_system_message` VALUES ('1397', ' }、帐号:{', 'who信息');
INSERT INTO `william_system_message` VALUES ('1398', ' }', 'who信息');
INSERT INTO `william_system_message` VALUES ('1399', '-warp 1-7(城市传送命令), -karma(友好度查询命令), -buff(加效果命令), -bug(错误及问题提交命令), -help(帮助信息)', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1400', '-warp 1-7(城市传送命令), -karma(友好度查询命令), -bug(错误及问题提交命令), -help(帮助信息)', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1401', '您必须等级在45以上才能使用命令!!!.', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1402', '玩家加效果命令已关闭.', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1403', '服务器已关闭-warp命令.', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1404', '此地图不能使用-warp命令.', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1405', '只能输入-warp 1-7之间的数字.', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1406', '-warp 1-说话岛, 2-银骑士, 3-奇岩, 4-威顿, 5-欧瑞, 6-燃柳村, 7-沉默洞穴', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1407', '此状态不能使用-warp命令.', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1408', '请写下游戏问题,格式:-bug 您需要写的问题.', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1409', '游戏问题已记录. 谢谢您提供的问题!', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1410', '不能读取BUG报告: (\'', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1411', '你的友好度点数为: ', '玩家命令信息');
INSERT INTO `william_system_message` VALUES ('1412', ' 受到', 'L1Atttack、L1Magic攻击信息');
INSERT INTO `william_system_message` VALUES ('1413', '命中率', 'L1Atttack攻击信息');
INSERT INTO `william_system_message` VALUES ('1414', '%  剩下', 'L1Atttack攻击信息');
INSERT INTO `william_system_message` VALUES ('1415', ' 伤害', 'L1Atttack、L1Magic攻击信息');
INSERT INTO `william_system_message` VALUES ('1416', '攻击失败', 'L1Atttack攻击信息');
INSERT INTO `william_system_message` VALUES ('1417', '★玩家【', '赌博PK胜利信息');
INSERT INTO `william_system_message` VALUES ('1418', '】把玩家', '赌博PK胜利信息');
INSERT INTO `william_system_message` VALUES ('1419', '】在赌博PK赛中日死了,真爽!', '赌博PK胜利信息');
INSERT INTO `william_system_message` VALUES ('1420', '地上的物品10秒后清除', '自动清除物品信息');
INSERT INTO `william_system_message` VALUES ('1421', '地上的物品被清除了', '自动清除物品信息');
INSERT INTO `william_system_message` VALUES ('1422', ' 剩下', 'L1Magic攻击信息');
INSERT INTO `william_system_message` VALUES ('1423', '您所选的比赛只有Lv', '宠物竞赛信息');
INSERT INTO `william_system_message` VALUES ('1424', '~Lv', '宠物竞赛信息');
INSERT INTO `william_system_message` VALUES ('1425', '的可参与', '宠物竞赛信息');
INSERT INTO `william_system_message` VALUES ('1426', '您所选的比赛需要物品 ', '宠物竞赛信息');
INSERT INTO `william_system_message` VALUES ('1427', ' 个不足', '宠物竞赛信息');
INSERT INTO `william_system_message` VALUES ('1428', '游戏人数已达上限', '宠物竞赛信息');
INSERT INTO `william_system_message` VALUES ('1429', '无限大战', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1430', '黑妖 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1431', '法师 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1432', '妖精 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1433', '骑士 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1434', '王族 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1435', '龙骑士 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1436', '幻术师 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1437', '男 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1438', '女 ', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1439', '可以', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1440', '不可以', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1441', '(邪恶者)', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1442', '(中立者)', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1443', '(正义者)', '无限大战看板信息');
INSERT INTO `william_system_message` VALUES ('1444', '怪物出現在', '随机出怪信息');
INSERT INTO `william_system_message` VALUES ('1445', ' MapID=', '随机出怪信息');
INSERT INTO `william_system_message` VALUES ('1446', ' X=', '随机出怪信息');
INSERT INTO `william_system_message` VALUES ('1447', ' Y=', '随机出怪信息');
INSERT INTO `william_system_message` VALUES ('1448', '新鲜的鱼饵似乎被啃食著。', '钓鱼提示信息');
INSERT INTO `william_system_message` VALUES ('1449', '服务器将于', '关机信息');
INSERT INTO `william_system_message` VALUES ('1450', '分钟后重启!!', '关机信息');
INSERT INTO `william_system_message` VALUES ('1451', '秒后重启!!', '关机信息');
INSERT INTO `william_system_message` VALUES ('1452', 'fR[******] ', '无限大战信息');
INSERT INTO `william_system_message` VALUES ('1453', ' 的无限大战将在5分钟后开始.', '无限大战信息');
INSERT INTO `william_system_message` VALUES ('1454', '您的功勋不足,军阶无法提升。', 'c_who');
INSERT INTO `william_system_message` VALUES ('1463', '☆距离服务器重开时间还有 ', 'c_who');
INSERT INTO `william_system_message` VALUES ('1464', ' 小时 ', 'c_who');
INSERT INTO `william_system_message` VALUES ('1465', '☆☆欢迎您来到希腊天堂,客服QQ:159772010☆☆', 'c_who');
INSERT INTO `william_system_message` VALUES ('1466', '服务器自动重启。', 'L1GameRestart');
INSERT INTO `william_system_message` VALUES ('1467', '如果回答错误就会被T下线', '外挂检测提示信息');
INSERT INTO `william_system_message` VALUES ('1468', '请输入', '外挂检测提示信息');
INSERT INTO `william_system_message` VALUES ('1469', '并按下回车确认', '外挂检测提示信息');
INSERT INTO `william_system_message` VALUES ('1470', 'fR AI外挂检测程序启动,请您在1分钟之内完成答题,超过1分钟将会被系统判定为挂机T下线,请服用AI药水获得题目！', '外挂检测提示信息');
INSERT INTO `william_system_message` VALUES ('1471', '请参赛者各就各位，赌博PK赛正式比赛中...', '赌博PK信息');
INSERT INTO `william_system_message` VALUES ('1472', '经验药水效果消失！', '经验药水结束信息');
INSERT INTO `william_system_message` VALUES ('1473', '你挑战的活动时间已结束!', '挑战活动结束信息');
INSERT INTO `william_system_message` VALUES ('1474', '出租时间还剩余 5分钟。', '旅馆出租结束信息');
INSERT INTO `william_system_message` VALUES ('1475', '出租时间还剩余 3分钟。', '旅馆出租结束信息');
INSERT INTO `william_system_message` VALUES ('1476', '出租时间还剩余 2分钟。', '旅馆出租结束信息');
INSERT INTO `william_system_message` VALUES ('1477', '出租时间还剩余 1分钟。', '旅馆出租结束信息');
INSERT INTO `william_system_message` VALUES ('1478', '个', '装备强化个数信息');
INSERT INTO `william_system_message` VALUES ('1479', '恭喜你答对了！', '外挂检测提示信息');
INSERT INTO `william_system_message` VALUES ('2020', '账号', null);
INSERT INTO `william_system_message` VALUES ('2021', '赠送物品', null);
INSERT INTO `william_system_message` VALUES ('2022', '玩家名字', null);
INSERT INTO `william_system_message` VALUES ('2000', '服务器设置', null);
INSERT INTO `william_system_message` VALUES ('2001', '注册设置', null);
INSERT INTO `william_system_message` VALUES ('2002', '最大玩家', null);
INSERT INTO `william_system_message` VALUES ('2003', '全体聊天', null);
INSERT INTO `william_system_message` VALUES ('2004', '负重倍率', null);
INSERT INTO `william_system_message` VALUES ('2005', '正义倍率', null);
INSERT INTO `william_system_message` VALUES ('2006', '自动注册', null);
INSERT INTO `william_system_message` VALUES ('2007', '手工注册', null);
INSERT INTO `william_system_message` VALUES ('2008', '冲武几率', null);
INSERT INTO `william_system_message` VALUES ('2009', '冲防几率', null);
INSERT INTO `william_system_message` VALUES ('2010', '经验倍率', null);
INSERT INTO `william_system_message` VALUES ('2011', '掉宝倍率', null);
INSERT INTO `william_system_message` VALUES ('2012', '掉钱倍率', null);
INSERT INTO `william_system_message` VALUES ('2013', '取消', null);
INSERT INTO `william_system_message` VALUES ('2014', '确定', null);
INSERT INTO `william_system_message` VALUES ('2015', '新建账号', null);
INSERT INTO `william_system_message` VALUES ('2016', '取消', null);
INSERT INTO `william_system_message` VALUES ('2017', '确定', null);
INSERT INTO `william_system_message` VALUES ('2018', '密码', null);
INSERT INTO `william_system_message` VALUES ('2019', 'GM设置', null);
INSERT INTO `william_system_message` VALUES ('1480', '元宝不足', '元宝商人_购买无元宝提示信息');
INSERT INTO `william_system_message` VALUES ('1481', '牧羊犬', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1482', '猫', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1483', '熊', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1484', '杜宾狗', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1485', '狼', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1486', '浣熊', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1487', '小猎犬', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1488', '圣伯纳犬', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1489', '狐狸', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1490', '暴走兔', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1491', '哈士奇', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1492', '柯利', '购买10级宠物S_ShopBuyList');
INSERT INTO `william_system_message` VALUES ('1493', '服务器即将重启。请移动至安全区域。', '关机提示GameServer');
INSERT INTO `william_system_message` VALUES ('1494', '服务器将会在', '关机提示GameServer');
INSERT INTO `william_system_message` VALUES ('1495', '秒后重启。请玩家先行离线。', '关机提示GameServer');
INSERT INTO `william_system_message` VALUES ('1496', '分后重启,请玩家先行离线。', '关机提示GameServer');
INSERT INTO `william_system_message` VALUES ('1497', '已取消服务器重启。服务器将会正常运作。', '取消关机提示GameServer');
INSERT INTO `william_system_message` VALUES ('1498', '玩家【', 'PK胜利公告信息');
INSERT INTO `william_system_message` VALUES ('1499', '】干净利落的解决了对手,赢此场比赛结束,请参赛者进行下一轮', 'PK胜利公告信息');
INSERT INTO `william_system_message` VALUES ('1500', '恭喜!你的银行存款账户,增加了1000万的收入!', 'PK胜利者信息');
INSERT INTO `william_system_message` VALUES ('1501', '恭喜!你得到了应该有的奖励!', 'PK胜利者信息');
INSERT INTO `william_system_message` VALUES ('1502', '比赛5分钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1503', '赌票开卖', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1504', '比赛3分钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1505', '比赛2分钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1506', '比赛1分钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1507', '比赛10秒钟钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1508', '比赛5秒钟钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1509', '比赛4秒钟钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1510', '比赛3秒钟钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1511', '比赛2秒钟钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1512', '比赛1秒钟钟后开始', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1513', '出发!', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1514', '赌博游戏开始.', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1515', '倍', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1516', '赌票即将关闭购买', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1517', '赌票关闭购买', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1518', '游戏没有开放.', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1519', '游戏正在准备中.', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1520', '食人妖精竞赛票', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1521', '正常', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1522', '食人妖精竞赛票 #', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1523', '食人妖精竞赛票 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1524', '第', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1525', '名 - ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1526', '赌肥游戏结束', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1527', '幸福 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1528', '快乐 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1529', '欢喜 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1530', '飞空鹿 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1531', '黄金毛皮 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1532', '夜之眼 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1533', '拉奇 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1534', '黑暗之火 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1535', '女神 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1536', '沙揉 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1537', '阴影 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1538', '那伊帕 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1539', '罗瑟莱得 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1540', '莱瑟必思 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1541', '钢铁尖牙 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1542', '洛基 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1543', '穿透 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1544', '波西顿 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1545', '莱瑟米娜 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1546', '星光 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1547', '怪力巨人 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1548', '凶猛的眼睛 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1549', '铁尖牙 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1550', '何摩思 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1551', '莱迈尔仑 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1552', '黑克津 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1553', '希娃 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1554', '泰特希 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1555', '沙如卡 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1556', '宙斯 ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1557', '\\fY时空裂痕即将开启.....', '时空裂痕信息');
INSERT INTO `william_system_message` VALUES ('1558', '\\fT时空裂痕在 ', '时空裂痕信息');
INSERT INTO `william_system_message` VALUES ('1559', ' 开启!!!异界侵略即将开始...', '时空裂痕信息');
INSERT INTO `william_system_message` VALUES ('1560', '\\fY时空裂痕关闭了。', '时空裂痕信息');
INSERT INTO `william_system_message` VALUES ('1561', '武器防爆卷最高只能点到50.', '防爆卷 武器');
INSERT INTO `william_system_message` VALUES ('1562', '防具防爆卷最高只能点到10.', '防爆卷 防具');
INSERT INTO `william_system_message` VALUES ('1563', '', '');
INSERT INTO `william_system_message` VALUES ('1564', '', '');
INSERT INTO `william_system_message` VALUES ('1565', '', '');
INSERT INTO `william_system_message` VALUES ('1566', '', '');
INSERT INTO `william_system_message` VALUES ('1567', '', '');
INSERT INTO `william_system_message` VALUES ('1568', '', '');
INSERT INTO `william_system_message` VALUES ('1569', '赔率: ', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1570', '游戏正在准备中.\r\n游戏正在进行中.', '赌肥信息');
INSERT INTO `william_system_message` VALUES ('1571', '不能攻击等级低於【', '新手保护系统信息');
INSERT INTO `william_system_message` VALUES ('1572', ' 】级的玩家', '新手保护系统信息');
INSERT INTO `william_system_message` VALUES ('1573', '等级未满【', '新手保护系统信息');
INSERT INTO `william_system_message` VALUES ('1574', ' 】级，其他玩家无法攻击您', '新手保护系统信息');
INSERT INTO `william_system_message` VALUES ('1575', '等级未满【', '新手保护系统信息');
INSERT INTO `william_system_message` VALUES ('1576', ' 】级，无法攻击其他玩家', '新手保护系统信息');
INSERT INTO `william_system_message` VALUES ('1577', '对方等级未满【', '新手保护系统信息');
INSERT INTO `william_system_message` VALUES ('1578', ' 】级，所以无法攻击您', '新手保护系统信息');
INSERT INTO `william_system_message` VALUES ('1579', '管理员', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1580', '一般武器排名', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1581', '稀有武器排名', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1582', '一般防具排名', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1583', '稀有防具排名', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1584', 'null', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1585', 'null', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1586', 'null', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1587', 'null', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1588', '个 ', '装备排行信息');
INSERT INTO `william_system_message` VALUES ('1589', '玩家排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1590', '1. 全部 排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1591', '2. 王族 排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1592', '3. 骑士 排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1593', '4. 妖精 排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1594', '5. 法师 排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1595', '6. 黑暗妖精 排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1596', '7. 龙骑士 排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1597', '8. 幻术师 排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1598', '全部排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1599', '王族排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1600', '骑士排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1601', '妖精排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1602', '法师排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1603', '黑妖排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1604', '龙骑士排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1605', '幻术师排行', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1606', '第', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1607', '名 ', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('1608', '空缺.', '玩家排行信息');
INSERT INTO `william_system_message` VALUES ('2024', '物品数量', null);
INSERT INTO `william_system_message` VALUES ('2023', '物品编号', null);
INSERT INTO `william_system_message` VALUES ('2025', '加成等级', null);
INSERT INTO `william_system_message` VALUES ('2026', '确定', null);
INSERT INTO `william_system_message` VALUES ('2027', '取消', null);
INSERT INTO `william_system_message` VALUES ('2028', '玩家列表', null);
INSERT INTO `william_system_message` VALUES ('2029', '变形', null);
INSERT INTO `william_system_message` VALUES ('2030', '玩家名字', null);
INSERT INTO `william_system_message` VALUES ('2031', '变形编号', null);
INSERT INTO `william_system_message` VALUES ('2032', '确定', null);
INSERT INTO `william_system_message` VALUES ('2033', '取消', null);
INSERT INTO `william_system_message` VALUES ('2034', '玩家列表', null);
INSERT INTO `william_system_message` VALUES ('2035', '变形列表', null);
INSERT INTO `william_system_message` VALUES ('1609', '等级尚未达到', '活动卷轴信息');
INSERT INTO `william_system_message` VALUES ('1610', '对方等级尚未达到', '活动卷轴信息');
INSERT INTO `william_system_message` VALUES ('1611', ' 级，所以无法组队', '活动卷轴信息');
INSERT INTO `william_system_message` VALUES ('1612', '您在活动区的时间到了', '活动卷轴信息');
INSERT INTO `william_system_message` VALUES ('1613', '现在不是活动时间,活动时间为每个星期六、日,早上九点到十一点', '活动卷轴信息');
INSERT INTO `william_system_message` VALUES ('1614', '您已经在活动区了', '活动卷轴信息');
INSERT INTO `william_system_message` VALUES ('1615', '您有( ', '活动卷轴信息');
INSERT INTO `william_system_message` VALUES ('1616', ' )分钟可待在活动区', '活动卷轴信息');
INSERT INTO `william_system_message` VALUES ('1617', '你不至于加那么多次吧!!', '玩家命令加多次错误提示');
INSERT INTO `william_system_message` VALUES ('2200', ' 买到了极品，消费天宝', '元宝购买公告提示');
INSERT INTO `william_system_message` VALUES ('2201', ' 回收了天宝', '回收元宝公告提示');
INSERT INTO `william_system_message` VALUES ('2202', '想骗我?送去去阿富汗.', '回收元宝需要物品不足提示');
INSERT INTO `william_system_message` VALUES ('2203', '已经复活.', 'BOSS复活提示');
INSERT INTO `william_system_message` VALUES ('1618', '恭喜你,已经学会爆击精通[1级]', '爆击精通学习信息');
INSERT INTO `william_system_message` VALUES ('1619', '恭喜你,已经学会爆击精通[2级]', '爆击精通学习信息');
INSERT INTO `william_system_message` VALUES ('1620', '恭喜你,已经学会爆击精通[3级]', '爆击精通学习信息');
INSERT INTO `william_system_message` VALUES ('1621', '恭喜你,已经学会爆击精通[4级]', '爆击精通学习信息');
INSERT INTO `william_system_message` VALUES ('1622', '恭喜你,已经学会爆击精通[5级]', '爆击精通学习信息');
INSERT INTO `william_system_message` VALUES ('20000', 'true', '商店买的装备鉴定与否true,false');
